language: python
sudo: false
python:
  - 2.7
  - 3.6
  - 3.5
  - 3.4
install:
  - pip install -U pip setuptools git+https://github.com/buildout/buildout.git@encapsulate-easy-install-env#egg=zc.buildout
  - buildout parts=test
script: bin/test
cache:
  directories:
    - $HOME/.cache/pip
    - eggs
before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
